const controlCommands = {
    nominal: [
        ".a16",
        ".a8",
        ".addr",
        ".align",
        ".asciiz",
        ".bankbytes",
        ".bss",
        ".charmap",
        ".code",
        ".constructor",
        ".data",
        ".dbyt",
        ".define",
        ".delmac", ".delmacro",
        ".destructor",
        ".dword",
        ".end",
        ".error",
        ".exitmac", ".exitmacro",
        ".export",
        ".exportzp",
        ".faraddr",
        ".fatal",
        ".fileopt", ".fopt",
        ".forceimport",
        ".global",
        ".globalzp",
        ".hibytes",
        ".i16",
        ".i8",
        ".import",
        ".importzp",
        ".incbin",
        ".include",
        ".interruptor",
        ".listbytes",
        ".literal",
        ".lobytes",
        ".local",
        ".localchar",
        ".macpack",
        ".org",
        ".out",
        ".p02",
        ".p4510",
        ".p816",
        ".pagelen", ".pagelength",
        ".pc02",
        ".pdtv",
        ".popcharmap",
        ".popcpu",
        ".popseg",
        ".psc02",
        ".pushcharmap",
        ".pushcpu",
        ".pushseg",
        ".referto", ".refto",
        ".reloc",
        ".res",
        ".rodata",
        ".segment",
        ".set",
        ".setcpu",
        ".tag",
        ".undef", ".undefine",
        ".warning",
        ".word",
        ".zeropage",
    ],
    togglableFeatures: [
        ".autoimport",
        ".case",
        ".debuginfo",
        ".linecont",
        ".smart",
    ],
    exceptional: [
        ".assert",
        ".condes",
        ".enum", ".endenum",
        ".feature",
        ".else",
        ".elseif",
        ".endif",
        ".list",
        ".mac", ".macro", ".endmac", ".endmacro",
        ".proc", ".endproc",
        ".repeat", ".endrep", ".endrepeat",
        ".scope", ".endscope",
        ".struct", ".endstruct",
        ".union", ".endunion",
    ],
    ifKeywords: [
        ".if",
        ".ifblank",
        ".ifconst",
        ".ifdef",
        ".ifnblank",
        ".ifndef",
        ".ifnref",
        ".ifref",
        ".ifp02",
        ".ifp4510",
        ".ifp816",
        ".ifpc02",
        ".ifpdtv",
        ".ifsc02",
    ],
    storageAllocators: [
        "byt", ".byte",
        ".res",
        ".dbyte",
        ".word",
        ".addr",
        ".faraddr",
        ".dword",
    ],
    compatibilityFeatures: [
        "at_in_identifiers",
        "bracket_as_indirect",
        "c_comments",
        "dollar_in_identifiers",
        "dollar_is_pc",
        "force_range",
        "labels_without_colons",
        "leading_dot_in_identifiers",
        "long_jsr_jmp_rts",
        "loose_char_term",
        "loose_string_term",
        "missing_char_term",
        "org_per_seg",
        "pc_assignment",
        "string_escapes",
        "ubiquitous_idents",
        "underline_in_numbers",
    ]
};

controlCommands.exceptional = [
    ...controlCommands.exceptional,
    ...controlCommands.ifKeywords,
    ...controlCommands.storageAllocators,
]

module.exports = controlCommands
