#!/bin/zsh

CLEAR="\x1b[0m"

RED="\x1b[1;31m"
GREEN="\x1b[1;32m"
BLUE="\x1b[1;34m"

UNDERLINE="\x1b[4m"
UNUNDERLINE="\x1b[24m"

error () {
    >&2 echo -e "$RED" "ERROR: $1$CLEAR"
    exit -1
}

branch-is () {
    if (( $# < 1 )); then
        error "branch name needed"
    fi

    CURRENT=$(git branch --show-current)

    if [[ $CURRENT == $1 ]]; then
        return 0
    else
        return 1
    fi
}

if (! (branch-is "main") ) ; then
    error "Branch is not 'main'. Please switch to branch 'main' before publishing (\`git switch main\`)"
fi

npm publish --dry-run
